Repository ansible-middleware/jbcs, pull requests merged in 2023-12, with the labels that each got.

#6 Add missing become where needed
  roles/jbcs/tasks/install.yml
  roles/jbcs/tasks/main.yml
  roles/jbcs/tasks/ssl.yml
Labels: bugfixes

#8 Set minimum ansible-core version to 2.14
  README.md
  meta/runtime.yml
  molecule/default/converge.yml
  molecule/default/prepare.yml
  roles/jbcs/defaults/main.yml
  roles/jbcs/handlers/main.yml
  roles/jbcs/meta/argument_specs.yml
  roles/jbcs/meta/main.yml
  roles/jbcs/tasks/fastpackages.yml
  roles/jbcs/tasks/firewalld.yml
  roles/jbcs/tasks/install.yml
  roles/jbcs/tasks/main.yml
  roles/jbcs/tasks/ssl.yml
Labels: major_changes

#9 Implement automatic download and install of security patches
  roles/jbcs/README.md
  roles/jbcs/defaults/main.yml
  roles/jbcs/meta/argument_specs.yml
  roles/jbcs/meta/main.yml
  roles/jbcs/tasks/install.yml
  roles/jbcs/tasks/main.yml
  roles/jbcs/tasks/patch.yml
  roles/jbcs/tasks/post_install.yml
Labels: minor_changes
